### ISSUE TITLE
Is there any plan to upgrade from gcc 8.2 to gcc 9.2?

### ISSUE THREAD

**Issue by zhouxs1023** [travisg/toolchains#25]
I like this shell script and newos very much, gcc 9.2 had released,Is there any plan to upgrade from gcc 8.2 to gcc 9.2?

**Comment by travisg** [comment]
Yah, there is. I should sit down and give it some time. Trouble is the ARM patches don't work as well 8.x and above, and may require some additional work for the multilib stuff. I have some patches incoming from some external contributors but I never integrated and tested. I'll try to get to this soon, thanks for reminding me.

Also, thanks for using it! I forget that people actually use this thing sometimes.

**Comment by zhouxs1023** [comment]
Thank you for your reply!
