### ISSUE TITLE
cross compiler toolchains size

### ISSUE THREAD

**Issue by zhouxs1023** [travisg/toolchains#26]
OS  : Ubuntu 19.04
Branches 8.2 : GCCVER=8.2.0 + BINVER=2.31.1 

I use cmd:  ./doit -f -a "i386"
the size of my cross-compiler is too big(about 950M) , Can you tell me how to reduce size of cross-compiler tools?

![360-165110079311486](https://user-images.githubusercontent.com/905931/66056846-57922380-e56a-11e9-8056-256810b7187a.png)
![360-16501110076462](https://user-images.githubusercontent.com/905931/66056870-5f51c800-e56a-11e9-92ef-dfdd23665749.png)

**Comment by zhouxs1023** [comment]
I  use  cmd:./doit  -f  -s  -a "i386"  reduce size

**Comment by travisg** [comment]
Ah yes, sorry for missing it. You need to use -s to strip it. It doesn't do it by default in case you need to debug the binary.
